### ISSUE TITLE
Does Omega support MSX-AUDIO (Y8950)?

### ISSUE THREAD

**Issue by denjhang** [skiselev/omega#17]
Does Omega support MSX-AUDIO (Y8950)?

**Comment by skiselev** [comment]
It should work with an MSX-Audio cartridge. I am unsure if it needs +12V/-12V. If it does, you might need to install a DC-DC convertor

**Comment by skiselev** [comment]
Martin Lukasek documented building a +12V/-12V DC-DC adapter here:
https://www.8bity.cz/2020/power-module-12v-for-omega-home-computer/
