### ISSUE TITLE
LS vs HCT

### ISSUE THREAD

**Issue by NuClear235** [skiselev/omega#20]
Orginal design was complete 74LS chips. Now are some replaced by 74HCT chips. 
Is it OK mix it so? Could not I wait problems?
Would not be best use all just all 74HCTs?
(Except special F and other exceptions)

**Comment by skiselev** [comment]
74LS was the best (higher speed/lower power consumption) logic family available back in early 80's when MSX was originally designed. 74HC/74HCT are slightly newer and they use fairly fast, and very low power CMOS technology. So I prefer using it in my designs.
Generally 74LS and 74HCT have comparable parameters and in most cases can be used interchangeably (but not 74HC, which is not TTL compatible).
Omega uses 74F for driving slot signals, as this logic family is fast and can drive higher loads. You could use 74HCT instead. Omega also uses a single 74LS07 open collector driver. That part is not available in 74HCT series.
