### ISSUE TITLE
About C68,C69 and C70

### ISSUE THREAD

**Issue by Bobitsme** [skiselev/omega#21]
Hi. 20 years ago, i owned of a NMS8250+FM pac and many disk and catridges. I keep good memory of time passed on it and happy to (try to) make a new one. So, really thank you for sharing your work.
I have a question about C68, C69 and C70:
On the bill of materials, you wrote that they are 10uF MLCC (not polarized). I have seen on this [website](https://msxmakers.design.blog/proyectos/omega-home-computer/omega-paso-a-paso/) that he put polarized capa.
I owned a 1.4 PCB. I trust you more than this website but i'm a bit uncertain :)

I have avoided a disaster with mine 2N2907 who have emitter and collector reversed compared to PN2907... my fault to use old component.

Thanks.

**Comment by skiselev** [comment]
You can use either non-polarized ceramic (MLCC) caps, or polarized tantalum or aluminum electrolytic capacitors. If using polarized caps, make sure to observe their polarity.
