### ISSUE TITLE
Key caps

### ISSUE THREAD

**Issue by alex3331** [skiselev/omega#23]
Can you please advise on how to get keycaps and how to label them?
Thanks

**Comment by skiselev** [comment]
Omega uses standard 102 key keyboard keycaps, for example, like these: https://www.amazon.com/Tecware-Keycaps-Double-Shot-Mechanical-Keyboards/dp/B08N6F23YT

**Comment by Bobitsme** [comment]
I have boughted this keyboard : [https://www.banggood.com/fr/BAJEAL-K300-87-Keys-Mechanical-Keyboard-USB-Wired-Hot-Swappable-Blue-Swtich-Colorful-LED-Backlight-Gaming-Keyboard-for-Gaming-Typing-Office-p-1863338.html?rmmds=myorder](url)
and this kit for the stabilizer : [https://www.ebay.fr/itm/233841619481](url)
