### ISSUE TITLE
source of V9958

### ISSUE THREAD

**Issue by alex3331** [skiselev/omega#25]
There are plenty of offerings on eBay - can you recommend one that you used and i was OK?
Heard a lot about relabeled chips.
If I will use just RGB - do I need CXA1645P?

**Comment by skiselev** [comment]
You still need CXA1645P for the RGB... It might be some other ways to buffer the RGB signals coming out from the VDP, but I haven't tested any.
As for V9958 source, I bought some from polida2008 while back, they work just fine
