### ISSUE TITLE
PCB Boards

### ISSUE THREAD

**Issue by alex3331** [skiselev/omega#26]
I am planning to order 5 each of PCB for mainboard and keyboard from JLCPCB.  I only need 2 of each. Is anybody interested in purchasing the rest? I am in Massachusetts, US.
Thanks

**Comment by skiselev** [comment]
I still have a few. Maybe it will be more price effective to get them from me... Faster for sure... I am located in Oregon
https://www.tindie.com/products/weird/omega-home-computer-pcbs/
