### ISSUE TITLE
Installing different video chips

### ISSUE THREAD

**Issue by Wierzbowsky** [skiselev/omega#3]
The spec claims that the board either takes v9938 or v9958 chip. But these chips have slightly different pinout. For example when installing v9958 instead of v9938 on Russian MSXs made by Yamaha, several additional wires need to be soldered. Also a diode needs to be installed between Z80 and v9958. How do you plan to solve these issues on the same board?

**Comment by skiselev** [comment]
These issues are already solved :-)
There are three major differences between V9938 and V9958 pinout:
1. Pin 21 - V9938 uses this pin as composite video output, V9958 uses it as power supply for video DAC. Omega has a a jumper JP3 that allows switching between these two functions
2. Pin 26 - V9938 can use this pin as a light pen switch input. V9958 uses it as /WAIT signal to CPU. In Omega this pin is connected to a pull-up resistor and to the WAIT circuit. As the result, with V9938 this pin remains logic "high" and does not affect system operation. V9958 would pull this pin "low" when it needs a wait state, and that would result in the CPU /WAIT pin becoming "low" as well.
3. Pin 5 - Both V9938 and V9958 use this as CSYNC output. The output voltage levels are different though. V9938 outputs about 2.5 V for "low' and about 5V for "high", while V9958 outputs standard TTL logic levels. In Omega this pin is connected to an emitter follower and then 74HC04 NOT gate. That should work in either case.
