### ISSUE TITLE
Position C93 must be jumped if the optional PAL clock generator is not installed

### ISSUE THREAD

**Issue by sdsnatcher** [skiselev/omega#40]
It's implicit in the schematic, but since most people won't know this, it's better to include a note there to explain that the position C93 must be jumped closed when the optional PAL clock generator isn't installed.

**Comment by skiselev** [comment]
That would be the case only if U43 is installed, eg. using V9938 VDP. I'll add a note

**Comment by skiselev** [comment]
Documented here: https://github.com/skiselev/omega/commit/fb3b31dc1fc799c4046cd5436b77a6c39a7dd5c3
