### ISSUE TITLE
Any reason for JP7 and RR10 to exist?

### ISSUE THREAD

**Issue by sdsnatcher** [skiselev/omega#41]
Is there any reason for JP7 and RR10 to exist? They only seem to be a source of trouble for those that I'm seeing to assemble the project.

Some of them cut the JP7 tracks open, causing mirroring of the 512KB of RAM to happen amongst the Memory Mapper pages. This is an unwanted behavior that causes some programs to incorrectly detect up to 4096KB of RAM from the 512KB RAM chip.

**Comment by skiselev** [comment]
Yes, there is a reason. The previous revisions (1.1, 1.2) didn't have JP7, JP8, and RR10. This resulted in some poorly written software (Jordi/MSXMaker knows exactly which) to misdetect the memory size. If I recall correctly, the software relied on writing and reading back page register, which supposedly should wrap around when the top of the memory is reached. In case previous revisions, the page register has 8-bit, while only 5 bits are used on a 512 KB system. So we added these jumpers.
Perhaps I should document them better...

**Comment by skiselev** [comment]
Some other software, detected the memory size by writing values to all 256 theoretical memory pages, and then reading the written values back, expecting that the values will be overwritten at some point, if the memory size is less than 4 MB. In case of the earlier Omega design, the writes above 512 KB (32 pages) simply disappear, which was causing issues.

**Comment by skiselev** [comment]
![error_U15](https://user-images.githubusercontent.com/11326662/210892856-4c6335e6-8908-4a57-aacc-a38fb4b6f9a0.jpg)
This shows the "testmap.com" output that displays an error, before implementing the "fix". Generally speaking, the software shouldn't read the page register back and rely on its value... but it does...
