### ISSUE TITLE
Keyboard LEDs

### ISSUE THREAD

**Issue by peterw8102** [skiselev/omega#47]
The keyboard has D2 and D3 as 3mm LEDs (through hole 3mm from the BOM). I can't see how these work with the MX Cherry Switches in the BOM. There's no room for the LED. I'm assuming I'm missing something? I thought I'd bought the right switches. Any help appreciated.

**Comment by skiselev** [comment]
Hope this explains :)
You'll want to get a flangeless 3 mm LEDs. See the BOM for some suggested part numbers. 
If for some reason your keys don't have a place to mount LED, perhaps you don't have the original Cherry MX switches?
![Cherry_MX_LED](https://user-images.githubusercontent.com/11326662/224400995-43a4d27f-4adc-4431-bfdd-63c89b514872.png)

**Comment by peterw8102** [comment]
Brilliant, I do have the right switches and had completely missed those holes! Thank you!
